# https://taskfile.dev

version: "3"

vars:
  PROJECT: maya

tasks:

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push || true

  deploy:
    desc: shortcut for stop -> push -> pull -> restart
    cmds:
      - task: stop
      - task: push
      - task: pull
      - task: install
      - task: restart

  cli:
    desc: run flask cli locally
    cmds:
      - poetry run flask cli {{.CLI_ARGS}}

# pip install --no-binary :all: grpcio --ignore-installed and pip install --no-binary :all: grpcio-tools --ignore-installed